keys:
  - &userkey age1xclkkc3hayk8hsrzl2fx6u3wvh7fr3zyart9auxcdzraeu3thyvsukepcc
creation_rules:
  - path_regex: "^(env/.*|keys/.*)$"
    binary: true
    key_groups:
      - age:
          - *userkey
